const sentences = [
    "Cory Zanoni is going to town on a tub of yoghurt.",
    "Cory Zanoni fell down a well in '04 and just stayed there.",
    "Cory Zanoni has been on the run from the federales for 13 years and shows no signs of slowing down.",
    "Cory Zanoni yearns to be known as a 'hat guy'.",
	"Cory Zanoni has never been stung by a bee and lives in fear of that changing.",
	"Cory Zanoni is a friend to all birds.",
	"Cory Zanoni very clearly wants someone to ask about the pin he's wearing.",
	"Cory Zanoni spent 14 weeks trying to make 'well aint that a pile of thistles' his catchphrase.",
	"Cory Zanoni is stuck in the crawl space again.",
	"Cory Zanoni stumbled and couldn't play it off.",
	"Cory Zanoni insists on playing Monopoly without any house rules.",
	"Cory Zanoni needs help fishing the drawstring out of his jacket hood.",
	"Cory Zanoni just can't find a pen for the life of him.",
	"Cory Zanoni is sure his keys are around here somewhere.",
	"Cory Zanoni is desperate for a nickname.",
	"Cory Zanoni swears he lost that game of Connect 4 to a 7 year old on purpose.",
	"Cory Zanoni spent the weekend practicing his whistlin' and is no better for it.",
	"Cory Zanoni accidentally tied his shoe laces together.",
	"Cory Zanoni needs you to be impressed by his collection of delicious teas.",
	"Cory Zanoni clearly thought you’d have laughed at least once by this point in the story.",
	"Cory Zanoni definitely won’t stick the landing in this anecdote.",
	"Cory Zanoni got lost no less than five times trying to get here tonight.",
	"Cory Zanoni just realised his punchline didn’t get a laugh and is now trying to act like it was just part of the set-up.",
	"Cory Zanoni is somehow both weirdly sweaty and awkwardly dry.",
	"Cory Zanoni is, in fact, only 45% water.",
	"Cory Zanoni misses the days when ‘likes coffee’ was enough personality to get by.",
	"Cory Zanoni resists the urge to talk about his cats whenever someone mentions their kids.",
	"Cory Zanoni has been singing ‘How You Remind Me’ by Nickleback for 3 hours alone in a karaoke booth.",
	"Cory Zanoni is terrified that a goatee would suit him.",
	"Cory Zanoni has unjustified opinions about colour grading.",
	"Cory Zanoni is still kind of annoyed by the Gossip Girl reveal.",
	"Cory Zanoni searched for 'wigs for men?' five seperate times last week."
];

document.getElementById("random-sentence").textContent = 
    sentences[Math.floor(Math.random() * sentences.length)];
